### ISSUE TITLE
http: panic serving [::1]:56425: runtime error: invalid memory address or nil pointer dereference goroutine 68 [running]:

### ISSUE THREAD

**Issue by kenzo-tanaka** [kenzoukenzou/golang-webapp#5]
クライアントが退出しました。
2020/09/28 22:07:42 http: panic serving [::1]:56425: runtime error: invalid memory address or nil pointer dereference
goroutine 68 [running]:
net/http.(*conn).serve.func1(0xc00053c000)
        /usr/local/Cellar/go/1.14.3/libexec/src/net/http/server.go:1772 +0x139
panic(0x1532040, 0x1a1b310)
        /usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:975 +0x3e3
main.(*client).read(0xc0003f2340)
        /Users/tanakakenzou/go/src/golang-webapp/chap2/chat/client.go:21 +0x7d
main.(*room).ServeHTTP(0xc000192450, 0x16a3700, 0xc000544000, 0xc0000a2500)
        /Users/tanakakenzou/go/src/golang-webapp/chap2/chat/room.go:85 +0x2d8
net/http.(*ServeMux).ServeHTTP(0x1a2cce0, 0x16a3700, 0xc000544000, 0xc0000a2500)
        /usr/local/Cellar/go/1.14.3/libexec/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0001b8000, 0x16a3700, 0xc000544000, 0xc0000a2500)
        /usr/local/Cellar/go/1.14.3/libexec/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc00053c000, 0x16a4e00, 0xc0004ee040)
        /usr/local/Cellar/go/1.14.3/libexec/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.14.3/libexec/src/net/http/server.go:2933 +0x35c

**Comment by kenzo-tanaka** [comment]
fixed
